services:

 flask:
   build: ./backend
   container_name : todex_flask
   ports: 
   - "5000:5000"
   environment:
   - DATABASE_URL=postgresql://tripti:abcd123@db:5432/todex
   depends_on:
    db:
     condition: service_healthy
   restart: always

 db:
  image : postgres:15
  container_name: todex_db
  environment:
    POSTGRES_USER : tripti 
    POSTGRES_PASSWORD : abcd123
    POSTGRES_DB : todex
  ports:
    - "5432:5432"
  volumes:
    - postgres_data:/var/lib/postgresql/data
  healthcheck:
    test: ["CMD-SHELL" , "pg_isready -U tripti -d todex"]
    interval : 5s
    timeout : 5s
    retries: 5

volumes:
  postgres_data:
  
    